# Zero-shot-ready

# AR parameters such as FFT parameters.
audio_repr: ar_laionclap.AR_LAIONCLAP
weight_file: 
feature_d: 768
sample_rate: 48000

# Model specific parameters.

# Linear evaluation/Fine-tuning common parameters.

# Linear evaluaition parameters.
batch_size: 128
lr_lineareval: 0.0003
report_per_epochs: 50
early_stop_epochs: 20

# Fine-tuning parameters.
warmup_epochs: 5
mixup: 0.5
ft_bs: 128
ft_lr: 2.0
ft_early_stop_epochs: -1  # -1: no early stopping
ft_epochs: 200
ft_freq_mask: 8
ft_time_mask: 64
ft_noise: 0.0
ft_rrc: True
